CLASS zcl_zepm_bp_mpc_ext DEFINITION
  PUBLIC
  INHERITING FROM zcl_zepm_bp_mpc
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_zepm_bp_mpc_ext IMPLEMENTATION.
ENDCLASS.
